title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: Be sure to come at my Online Fortnite Course everyday!

# social links
twitter_username: RSean349 # DO NOT include the @ character, or else the build will fail!
github_username:  CryptSean # DO NOT include the @ character, or else the build will fail!
twitch_username:  rise_sean2

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
